# https://www.playframework.com/documentation/latest/Configuration

python.engine.url = "http://localhost:8000"
python.engine.url = ${?PYTHON_ENGINE_URL}

play.filters.hosts {
  allowed = ["localhost:9000", "127.0.0.1:9000", "scala-backend:9000"]
}
