# https://www.playframework.com/documentation/latest/Configuration

python.engine.url = "http://localhost:8000"
python.engine.url = ${?PYTHON_ENGINE_URL}

play.http.secret.key = ${?APPLICATION_SECRET}
play.http.secret.key = ${?PLAY_HTTP_SECRET_KEY}

play.filters.hosts {
  allowed = [
    "localhost:9000",
    "127.0.0.1:9000",
    "scala-backend:9000",
    ".onrender.com"
  ]
}

play.filters.enabled += "play.filters.cors.CORSFilter"

play.filters.cors {
  allowedOrigins = [
    "http://localhost:5173",
    "http://localhost:9000",
    "https://localhost:5173",
    "https://localhost:9000",
    "https://diagnostico-frontendchatbot.vercel.app"
  ]
  allowedHttpMethods = ["GET", "POST", "OPTIONS"]
  allowedHttpHeaders = ["Content-Type", "Accept"]
}
