# https://www.playframework.com/documentation/latest/Configuration

python.engine.url = "http://localhost:8000"
python.engine.url = ${?PYTHON_ENGINE_URL}

play.http.secret.key = "UY4Bm9zPx7Lq2Vk8Rt5Nw3Jf6Hd1CsAe0GyObnMpXiQuSvWaKc"
play.http.secret.key = ${?APPLICATION_SECRET}

play.filters.hosts {
  allowed = ["localhost:9000", "127.0.0.1:9000", "scala-backend:9000"]
}

play.filters.enabled += "play.filters.cors.CORSFilter"

play.filters.cors {
  allowedOrigins = ["http://localhost:5173", "http://localhost:9000"]
  allowedHttpMethods = ["GET", "POST", "OPTIONS"]
  allowedHttpHeaders = ["Content-Type", "Accept"]
}
